services:
  apisix:
    image: apache/apisix:3.9.1-debian
    volumes:
      - ./config.yml:/usr/local/apisix/conf/config.yaml:ro
      - ./apisix.yml:/usr/local/apisix/conf/apisix.yaml:ro
    depends_on:
      - httpbin
    ports:
      - "9080:9080"
  httpbin:
    image: kennethreitz/httpbin
